<a href="https://colab.research.google.com/github/Aayush21037/aiml_bootcamp_2026/blob/main/Session4_data_tranformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()
import pandas as pd

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [29]:
import pandas as pd
df = pd.read_csv('session4_dummy_students_data.csv')


In [3]:
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  


In [4]:
print(df.columns)

Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score'],
      dtype='object')


In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB
None


In [6]:
print(df.describe())

       student_id        age       math    science    english  \
count    20.00000  20.000000  20.000000  20.000000  20.000000   
mean    110.50000  16.450000  69.500000  72.350000  72.200000   
std       5.91608   0.510418  18.446223  15.383775  17.157475   
min     101.00000  16.000000  35.000000  45.000000  42.000000   
25%     105.75000  16.000000  57.250000  60.000000  59.500000   
50%     110.50000  16.000000  73.000000  74.500000  75.500000   
75%     115.25000  17.000000  84.250000  85.250000  86.000000   
max     120.00000  17.000000  95.000000  93.000000  96.000000   

       attendance_percent  study_hours_per_week  assignments_submitted  \
count           20.000000             20.000000              20.000000   
mean            83.850000              7.250000               7.750000   
std             11.089469              3.092861               1.915999   
min             62.000000              2.000000               4.000000   
25%             76.500000              5.000

In [9]:
math_score = df['math'].to_numpy()
print(math_score)
print(math_score.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
69.5


In [11]:
science_score = df['science'].to_numpy()
print(science_score)

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]


In [12]:
eng_score = df['english'].to_numpy()
print(eng_score)

[69 94 58 81 47 90 66 89 51 85 72 79 42 91 60 96 65 83 46 80]


In [14]:
final_project_score = df['final_project_score'].to_numpy()
print(final_project_score)

[82 93 60 78 45 95 69 91 55 86 70 80 39 92 63 96 68 84 48 79]


In [15]:
avg_score=(math_score+science_score+eng_score+final_project_score)/4
print(avg_score)

[78.25 91.5  58.5  77.5  46.   91.5  67.25 91.75 52.75 82.5  68.   78.5
 40.25 89.5  58.75 93.5  65.75 83.   46.5  77.25]


In [22]:
df = pd.read_csv('session4_dummy_students_data.csv')
df['avg_score'] = avg_score
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  avg_score  
0                   82      78.25  
1                   93      91.50  
2                   60      58.50  
3                   78      77.50  
4                   45    

In [24]:
top_students = df[df['avg_score']>85]
print(top_students)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score  avg_score  
1                    93      91.50  
5                    95      91.50  
7                    91      91.75  
13                   92      89.50  
15             

In [26]:
low_attendance = df[df['attendance_percent'] < 75]
print(low_attendance)

    student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47   
8          109  Vivaan   17   Mumbai    48       57       51   
12         113     Dev   17   Mumbai    35       45       42   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
8                   71                     4                      6   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score  avg_score  
4                    45      46.00  
8                    55      52.75  
12                   39      40.25  
18                   48      46.50  


In [28]:
student_city = df[df['city'] == "Mathura"]
print(student_city)

    student_id    name  age     city  math  science  english  \
2          103   Kabir   17  Mathura    55       61       58   
6          107  Ishaan   17  Mathura    64       70       66   
10         111   Arjun   17  Mathura    67       63       72   
14         115   Kunal   17  Mathura    58       54       60   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
2                   75                     5                      6   
6                   82                     6                      7   
10                  80                     6                      8   
14                  77                     5                      6   
18                  66                     3                      5   

    final_project_score  avg_score  
2                    60      58.50  
6                    69      67.25  
10                   70      68.00  
14                   63      58.75  
18 

In [34]:
less_active = df[df['assignments_submitted']<6]
print(less_active)

    student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47   
12         113    Dev   17   Mumbai    35       45       42   
18         119   Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score  
4                    45  
12                   39  
18                   48  


In [35]:
df.to_csv('session4_dummy_students_data.csv',index = False)